#!/bin/bash

BASE="THEBASELOCATION"
COORDINATOR="THECOORDINATOR"
CLUSTERNAME="THECLUSTERNAME"
RANDOMSSHPORT="THERANDOMSSHPORT"

if [ "$#" -ne 2 ]; then
	echo "
==============================================================  
Params -: 
[1] (I)nclude / (E)xclude Coordinator 
[2] Password For User => vagrant

Write Command(s) => $BASE/matsya-vagvbox-sa-$CLUSTERNAME-exec 
==============================================================
    "
	exit
fi

ISFA="$BASE/matsya-vagvbox-sa-$CLUSTERNAME-exec"
if [ -f "$ISFA" ]
then
	echo ""
else
	echo "
==============================================================  
Params -: 
[1] (I)nclude / (E)xclude Coordinator 
[2] Password For User => vagrant

Write Command(s) => $BASE/matsya-vagvbox-sa-$CLUSTERNAME-exec 
==============================================================
    "
	exit
fi

for Config in $BASE/VagVBoxSA/$CLUSTERNAME/Configs/*; do
    if [ -d "$Config" ]; then
    	Config=${Config//$BASE/}
    	Config=${Config//VagVBoxSA/}
    	Config=${Config//$CLUSTERNAME/}
    	Config=${Config//Configs/}
    	Config=${Config//matsya-vagvbox-sa/}
    	Config=${Config//\//}
    	Config=${Config//-/.}
    	Config=${Config//../}
    	CHOICE=$1
    	if [ $CHOICE == "E" ] || [ $CHOICE == "e" ] ; then
		if [ $Config == "$COORDINATOR" ] || [ $Config == "$COORDINATOR" ] ; then
			Config="Coordinator"
		fi
	fi    	
	if [ $Config == "Coordinator" ] || [ $Config == "Coordinator" ] ; then
		echo ""
	else
		echo "---------------------"
		echo "$Config"
		echo "---------------------"
		echo 'Execution Started...'
		echo '~~~~~~~~~~~~~~~~~~~~~'
		RANDOMFILENAME=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 15 | head -n 1)
		sudo touch $BASE/VagVBoxSA/$CLUSTERNAME/$RANDOMFILENAME
		echo '#!/bin/bash
' | sudo tee -a $BASE/VagVBoxSA/$CLUSTERNAME/$RANDOMFILENAME > /dev/null
		sudo bash -c "cat $BASE/matsya-vagvbox-sa-$CLUSTERNAME-exec >> $BASE/VagVBoxSA/$CLUSTERNAME/$RANDOMFILENAME"
		sudo sshpass -p $2 scp -P $RANDOMSSHPORT $BASE/VagVBoxSA/$CLUSTERNAME/$RANDOMFILENAME vagrant@$Config:/home/vagrant
		sudo ssh vagrant@$Config -p $RANDOMSSHPORT  -o "StrictHostKeyChecking=no" -i "$BASE/matsya-vagvbox-sa-$CLUSTERNAME.pem" "sudo chmod 777 $RANDOMFILENAME && ./$RANDOMFILENAME && sudo rm -f $RANDOMFILENAME"
		sudo rm -f $BASE/VagVBoxSA/$CLUSTERNAME/$RANDOMFILENAME 
		echo '~~~~~~~~~~~~~~~~~~~~~'
		echo 'Execution Complete...'
		echo "---------------------"		
		echo ''
	fi    	
    fi
done


