#!/bin/bash

E2ERESPONSE=$(curl -X POST \
  'https://api.e2enetworks.com/myaccount/api/v1/nodes/?apikey=E2ETHEAPIKEY&location=E2ETHEVMLOCATION' \
  -H 'Authorization: Bearer     E2ETHEAUTHTOKEN' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: E2ETHETOKENNAME' \
  -H 'cache-control: no-cache' \
  -d '{"name":"E2ETHENAMEOFINSTANCE",
"region":"E2ETHEREGION",
"plan":"E2ETHEPLAN",
"image":"E2ETHEDISTRO",
"ssh_keys":["E2ETHESSHKEYS"],
"backups":false,
"disable_password":true}')

echo $E2ERESPONSE > E2ETHEPLACETOSAVERESPONSE
